# Generated by Django 6.0.2 on 2026-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
